name: Deploy AWS Infrastructure

on:
  push:
    branches: [ "Kien" ]

env:
  AWS_REGION: us-east-1
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production


    steps:
    #Checkout the code
    - name: Checkout
      uses: actions/checkout@v3

    #Config AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # aws-region: ${{ env.AWS_REGION }}

        aws-access-key-id: AKIA4DMVQHFMGWIGZB5M
        aws-secret-access-key: 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
        aws-region: ${{ env.AWS_REGION }}
    
    #Terraform Init
    - name: Initialization Terraform
      uses: hashicorp/NT548-lab2-group9-Terraform-GithubActions@Kien
      with:
        tf_actions_version: 1.9.8
        tf_actions_subcommand: 'init'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    