name: Deploy AWS Infrastructure

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      #Checkout the code
    - name: Checkout
      uses: actions/checkout@v3

      #Set up Python
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
   
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
    #Checkout the code
    - name: Checkout
      uses: actions/checkout@v3

    #Checkov terraform code
    - name: Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
    #Checkout the code
    - name: Checkout
      uses: actions/checkout@v3

    #Config AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  aws-region: ${{ env.AWS_REGION }} 

        aws-access-key-id: AKIARZDBIDVYMQM7UI64
        aws-secret-access-key: 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
        aws-region: ${{ env.AWS_REGION }}
    
    #Terraform Init
    - name: Terraform Initialization
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.8
        tf_actions_subcommand: 'init'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #Terraform Plan
    - name: Terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.8
        tf_actions_subcommand: 'plan'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #Terraform Apply
    - name: Terraform apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.8
        tf_actions_subcommand: 'apply'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    #Reinitialize Terraform with S3 backend
    - name: Reinitialize Terraform with S3 backend
      run: |
        chmod -R u+w .terraform
        echo 'terraform { backend "s3" { bucket = "s3statebackend-group9-3183" dynamodb_table = "state-lock" key = "global/mystatefile/terraform.tfstate" region = "us-east-1" encrypt = true } }' > backend.tf
        terraform init -reconfigure

    #Terraform destroy
    - name: Destroy Terraform resource
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.8
        tf_actions_subcommand: 'destroy'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


